name: Slow Tests On Pull

on:
  pull_request:
    branches:
        - main
        - prod
  workflow_dispatch:

permissions:
  contents: read
  checks: write
  actions: read

jobs:
  test-slow:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      - run: npm ci
      
      # Test Slow includes all tests
      - run: npm run test:slow -- --reporter=default --reporter=junit --outputFile=test-results/slow-node.xml
      - run: npm run test:slow:wrangler -- --reporter=default --reporter=junit --outputFile=test-results/slow-wrangler.xml

      # Upload Test Results
      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: slow-test-results
          path: test-results/*.xml

      # Generate Detailed Test Report
      - name: Test Report
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: Slow Tests On Pull
          path: test-results/*.xml
          reporter: java-junit
